// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

using DateOnlyApp.Classes;
using DateOnlyApp.Data.Configurations;
using DateOnlyApp.Models;
using Microsoft.EntityFrameworkCore;
using static ConfigurationLibrary.Classes.ConfigurationHelper;

namespace DateOnlyApp.Data
{
    public partial class Context : DbContext
    {
        public Context()
        {
        }

        public Context(DbContextOptions<Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Person> Person { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(ConnectionString());
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new PersonConfiguration());

            modelBuilder.HasSequence<int>("seq_test").HasMin(1);
            modelBuilder.Entity<Person>().HasData(
                new Person()
                {
                    PersonId = 1, 
                    FirstName = "Karen", 
                    LastName = "Payne", 
                    BirthDate = new DateOnly(1956,9,24)
                },
                new Person()
                {
                    PersonId = 2, 
                    FirstName = "Bob", 
                    LastName = "Smith", 
                    BirthDate = new DateOnly(1960, 2, 12)
                }
            );
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        // For pre EF Core 8
        //protected override void ConfigureConventions(ModelConfigurationBuilder builder)
        //{
        //    builder.Properties<DateOnly>()
        //        .HaveConversion<DateOnlyConverter>()
        //        .HaveColumnType("date");

        //    base.ConfigureConventions(builder);
        //}
    }
}
