// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;

namespace DateOnlyApp1.Models;

public partial class Person
{
    public int PersonId { get; set; }
    [Display(Name = "First")]
    public string FirstName { get; set; }
    [Display(Name = "Last")]
    public string LastName { get; set; }

    // see DbContext, ConfigureConventions
    [Display(Name = "Birth Date")]
    public DateOnly? BirthDate { get; set; }
}