// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DateOnlyApp.Models;

public partial class Person
{
    public int PersonId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    // see DbContext, ConfigureConventions
    public DateOnly? BirthDate { get; set; } 
}