// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using DateOnlyApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DateOnlyApp.Data.Configurations;

public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
{
    public void Configure(EntityTypeBuilder<Person> entity)
    {
        entity.Property(e => e.BirthDate).HasColumnType("date");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
}